# Generated by Django 2.2.2 on 2020-10-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emapp', '0003_auto_20201023_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
