# Generated by Django 2.2.2 on 2020-10-24 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emapp', '0004_customuser_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers_name', models.CharField(max_length=70)),
                ('customers_email', models.EmailField(max_length=100)),
                ('customers_phone', models.CharField(max_length=11)),
                ('product_type', models.CharField(choices=[('6 months', '6 months'), ('1 year', '1 Year')], max_length=100)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('reference', models.CharField(default='', max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
