# Generated by Django 2.2.2 on 2020-10-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emapp', '0005_payments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
