# Generated by Django 2.2.2 on 2020-10-26 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emapp', '0006_auto_20201024_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
